version: 2

sources:
  - name: raw
    database: wagon-bootcamp-385919
    schema: gz_raw_data
    loader: bigquery
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: date_date
        columns:
           - name: date_date
             description: date of purchase

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: id of the products
        tests:
          - unique:
              column_name: products_id

      - name: ship
        identifier: raw_gz_ship
      
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook

models:

  - name: int_sales_margin
    description: margin calculation per order line / product sales
    columns:
      - name: orders_id
        description: orders key
        tests:
          - not_null

      - name: products_id
        description: products key
        tests:
          - not_null

      - name: margin
        description: margin = revenue - purchase_cost
        tests:
          - not_null

      - name: purchase_cost
        description: purchase_cost = quantity * purchase_price
        tests:
          - not_null

      - name: date_date
        description: date of the order
        tests:
          - not_null

      - name: revenue
        description: revenue per order line
        tests:
          - not_null

      - name: quantity
        description: quantity per order line
        tests:
          - not_null

    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"


  - name: int_orders_margin
    description: margin calculation per order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null

      - name: margin
        description: margin = revenue - purchase_cost
        tests:
          - not_null

      - name: purchase_cost
        description: purchase_cost = quantity * purchase_price
        tests:
          - not_null

      - name: date_date
        description: date of the order
        tests:
          - not_null

      - name: revenue
        description: revenue per order
        tests:
          - not_null

      - name: quantity
        description: quantity per order
        tests:
          - not_null


  - name: int_orders_operational
    description: operational margin calculation per order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null

      - name: date_date
        description: date of the order
        tests:
          - not_null

      - name: operational_margin
        description: operational_margin = margin + shipping_fee - log_cost - ship_cost

      - name: quantity
        description: quantity per order
        tests:
          - not_null

      - name: revenue
        description: revenue per order
        tests:
          - not_null

      - name: purchase_cost
        description: purchase_cost = quantity * purchase_price
        tests:
          - not_null

      - name: margin
        description: margin = revenue - purchase_cost
        tests:
          - not_null

      - name: shipping_fee
        description: amount paid by customer for shipping

      - name: log_cost
        description: logistic preparation cost

      - name: ship_cost
        description: cost paid to carrier
  
  - name: int_campaigns
    description: data from all campaigns
    columns:
      - name: paid_source
        tests:
          - not_null
      - name: campaign_name
        tests:
          - not_null
    tests:
       - unique:
           column_name: "(campaign_key || '-' || date_date)"
  
  - name: finance_campaigns_day
    description: global kpi
    columns:
      - name: ads_margin
        description: operational_margin - ads_cost
        tests:
          - not_null
      - name: average_basket
        description: average basket cost for each day
        tests:
          - not_null