 version: 2

 sources:
   - name: raw
     database: wagon-bootcamp-385919
     schema: gz_raw_data
     loader: bigquery
     description: ...
     freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour} 
     tables:
      - name: sales
        identifier: raw_gz_sales
        loaded_at_field: updated_at
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship