version: 2

sources:
  - name: raw
    database: wagon-bootcamp-385919
    schema: gz_raw_data
    loader: bigquery
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: date_date
        columns:
           - name: date_date
             description: date of purchase

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: id of the products
        tests:
          - unique:
              column_name: products_id

      - name: ship
        identifier: raw_gz_ship
